//! Wiring the counter contract into `soro-fuzz-core`: this module is the
//! "one crate's worth of trait impls" contributors write per contract.

use arbitrary::Arbitrary;
use soroban_sdk::{
    testutils::{MockAuth, MockAuthInvoke},
    Address, Env, IntoVal,
};

use soro_fuzz_core::{
    AddressPool, Command, ContractAdapter, ExecContext, Invariant, InvariantCtx, Outcome,
    ReferenceModel, Violation,
};
use soro_fuzz_strategies::BoundedI128;

use crate::{CounterContract, CounterContractArgs, CounterContractClient};

/// Marker type for the counter contract; carries no state of its own.
pub struct CounterAdapter;

/// Shadow state: what we expect `get()` to return.
#[derive(Debug, Clone, Default)]
pub struct CounterModel {
    pub expected_count: i64,
}

impl ReferenceModel for CounterModel {}

/// `Set`'s payload is generated by `soro-fuzz-strategies`'s `BoundedI128`
/// rather than a plain `i64`: bounding it to exactly `i64`'s range (so the
/// cast to the contract's actual `i64` argument is lossless) while biasing
/// generation toward `i64::MIN`/`i64::MAX`/`0` gives the fuzzer a real shot
/// at hitting `set`'s edge cases instead of almost always picking values
/// deep in the middle of the range.
type SetValue = BoundedI128<{ i64::MIN as i128 }, { i64::MAX as i128 }>;

/// The counter's action space.
#[derive(Arbitrary, Debug, Clone)]
pub enum CounterCommand {
    Increment,
    Decrement,
    /// Admin-gated: resets the count to zero.
    Reset,
    /// Admin-gated: sets the count to an arbitrary value.
    Set(SetValue),
}

impl ContractAdapter for CounterAdapter {
    type Command = CounterCommand;
    type Model = CounterModel;

    fn setup(env: &Env, addresses: &AddressPool) -> (Address, Self::Model) {
        // contributors: this is where role assignment happens — here,
        // address 0 in the pool is always "the admin" the contract was
        // constructed with.
        let admin = addresses.get(0).clone();
        let contract_id = env.register(CounterContract, CounterContractArgs::__constructor(&admin));
        (contract_id, CounterModel::default())
    }
}

impl Command<CounterAdapter> for CounterCommand {
    fn execute(&self, ctx: &ExecContext, authorizers: &[Address]) -> Outcome {
        let admin = ctx.addresses.get(0).clone();
        let client = CounterContractClient::new(ctx.env, ctx.contract_id);

        match self {
            // No auth involved, so `required_auth_satisfied` is
            // unconditionally true: an Abort here can't be attributed to
            // withheld auth, so it can only be an undeclared bug.
            CounterCommand::Increment => {
                Outcome::from_try_result(client.try_increment(), true, |e| e as u32)
            }
            CounterCommand::Decrement => {
                Outcome::from_try_result(client.try_decrement(), true, |e| e as u32)
            }
            CounterCommand::Reset => {
                let auth_satisfied = mock_admin_auth(
                    ctx.env,
                    ctx.contract_id,
                    &admin,
                    authorizers,
                    "reset",
                    soroban_sdk::vec![ctx.env],
                );
                Outcome::from_try_result(client.try_reset(), auth_satisfied, |e| e as u32)
            }
            CounterCommand::Set(value) => {
                let value = value.get() as i64;
                let auth_satisfied = mock_admin_auth(
                    ctx.env,
                    ctx.contract_id,
                    &admin,
                    authorizers,
                    "set",
                    soroban_sdk::vec![ctx.env, value.into_val(ctx.env)],
                );
                Outcome::from_try_result(client.try_set(&value), auth_satisfied, |e| e as u32)
            }
        }
    }

    fn apply_to_model(
        &self,
        model: &mut CounterModel,
        _addresses: &AddressPool,
        outcome: &Outcome,
    ) {
        if !outcome.is_ok() {
            return;
        }
        match self {
            CounterCommand::Increment => {
                model.expected_count = model.expected_count.saturating_add(1)
            }
            CounterCommand::Decrement => {
                model.expected_count = model.expected_count.saturating_sub(1)
            }
            CounterCommand::Reset => model.expected_count = 0,
            CounterCommand::Set(value) => model.expected_count = value.get() as i64,
        }
    }
}

/// Contract-specific invariant (not every invariant needs to live in the
/// shared `soro-fuzz-invariants` crate — this one is meaningless outside
/// the counter contract): the on-chain count must always match the shadow
/// model's expectation.
pub struct CounterValueMatchesModel;

impl Invariant<CounterAdapter> for CounterValueMatchesModel {
    fn name(&self) -> &'static str {
        "counter-value-matches-model"
    }

    fn check(&self, ctx: &InvariantCtx<CounterAdapter>) -> Result<(), Violation> {
        let client = CounterContractClient::new(ctx.env, ctx.contract_id);
        let actual = client.get();
        if actual != ctx.model.expected_count {
            return Err(Violation {
                invariant: self.name(),
                message: format!(
                    "on-chain count {actual} != model's expected count {}",
                    ctx.model.expected_count
                ),
                step_index: ctx.step_index,
            });
        }
        Ok(())
    }
}

/// Mocks `admin`'s authorization for `contract_id.fn_name(args)` iff `admin`
/// is one of the addresses this step authorized; otherwise mocks nothing,
/// so the contract's `require_auth()` legitimately fails. Returns whether
/// auth was actually satisfied, so the caller can pass it to
/// `Outcome::from_try_result` and correctly distinguish an expected auth
/// rejection from an undeclared panic.
fn mock_admin_auth(
    env: &Env,
    contract_id: &Address,
    admin: &Address,
    authorizers: &[Address],
    fn_name: &str,
    args: soroban_sdk::Vec<soroban_sdk::Val>,
) -> bool {
    let satisfied = authorizers.contains(admin);
    if satisfied {
        let invoke = MockAuthInvoke {
            contract: contract_id,
            fn_name,
            args,
            sub_invokes: &[],
        };
        env.mock_auths(&[MockAuth {
            address: admin,
            invoke: &invoke,
        }]);
    } else {
        env.mock_auths(&[]);
    }
    satisfied
}

#[cfg(test)]
mod tests {
    use super::*;
    use soro_fuzz_core::{AuthSelection, Harness, Run, Step};

    fn harness() -> Harness<CounterAdapter> {
        Harness::<CounterAdapter>::new().with_invariant(CounterValueMatchesModel)
    }

    fn step(command: CounterCommand, authorized_indices: Vec<u8>) -> Step<CounterCommand> {
        Step {
            command,
            authorized: AuthSelection::from_indices(authorized_indices),
            advance_time: None,
        }
    }

    #[test]
    fn increment_then_decrement_round_trips() {
        let run = Run {
            steps: vec![
                step(CounterCommand::Increment, vec![]),
                step(CounterCommand::Increment, vec![]),
                step(CounterCommand::Decrement, vec![]),
            ],
        };
        assert!(harness().run(run).is_ok());
    }

    #[test]
    fn set_without_admin_auth_is_rejected_not_a_panic() {
        // Address 0 is the admin (see `CounterAdapter::setup`); authorizing
        // index 1 instead means the admin never signed, so `set` should be
        // host-rejected (Outcome::Rejected), not crash the run.
        let run = Run {
            steps: vec![step(CounterCommand::Set(SetValue::new(42)), vec![1])],
        };
        assert!(harness().run(run).is_ok());
    }

    #[test]
    fn set_with_admin_auth_succeeds() {
        let run = Run {
            steps: vec![step(CounterCommand::Set(SetValue::new(42)), vec![0])],
        };
        assert!(harness().run(run).is_ok());
    }

    #[test]
    fn single_decrement_from_initial_state_runs_clean() {
        let run = Run {
            steps: vec![step(CounterCommand::Decrement, vec![])],
        };
        assert!(harness().run(run).is_ok());
    }

    #[test]
    fn value_matches_model_invariant_catches_real_divergence() {
        // Exercise the invariant directly against a live contract, with a
        // shadow model deliberately built to disagree with it — proves
        // `CounterValueMatchesModel` actually detects the class of bug it
        // exists to catch, rather than only ever passing by construction.
        use soroban_sdk::testutils::Address as _;
        let env = Env::default();
        let admin = Address::generate(&env);
        let contract_id = env.register(CounterContract, CounterContractArgs::__constructor(&admin));
        let client = CounterContractClient::new(&env, &contract_id);
        client.increment();
        client.increment();

        let wrong_model = CounterModel { expected_count: 0 };
        let pool = AddressPool::generate(&env, 1);
        let ctx = InvariantCtx {
            env: &env,
            contract_id: &contract_id,
            model: &wrong_model,
            command: &CounterCommand::Increment,
            last_outcome: &Outcome::Ok,
            authorizers: &[],
            addresses: &pool,
            step_index: 0,
        };
        assert!(CounterValueMatchesModel.check(&ctx).is_err());
    }
}
#[cfg(test)]
mod broken_counter {
    //! Divergence-path proof (counterpart to core's `undeclared_panic_is_a_finding`):
    //! a deliberately broken counter whose `increment` adds 2 instead of 1, driven
    //! through the real `Harness` loop so the invariant is forced to fire. Proves the
    //! fuzzer catches a state-divergence bug end to end — not just that `.check()`
    //! returns `Err` when handed a wrong model in isolation.

    use super::{mock_admin_auth, CounterCommand, CounterModel};
    use soro_fuzz_core::{
        AddressPool, AuthSelection, Command, ContractAdapter, ExecContext, Harness, Invariant,
        InvariantCtx, Outcome, Run, Step, Violation,
    };
    use soroban_sdk::{
        contract, contracterror, contractimpl, symbol_short, Address, Env, IntoVal, Symbol,
    };

    const COUNT: Symbol = symbol_short!("COUNT");
    const ADMIN: Symbol = symbol_short!("ADMIN");

    #[contracterror]
    #[derive(Copy, Clone, Debug, Eq, PartialEq, PartialOrd, Ord)]
    #[repr(u32)]
    pub enum BrokenError {
        Overflow = 1,
        Underflow = 2,
    }

    /// Identical to `CounterContract` except `increment` adds 2 — so the model's
    /// expected `+1` and the on-chain `+2` disagree from the very first increment.
    #[contract]
    pub struct BrokenCounterContract;

    #[contractimpl]
    impl BrokenCounterContract {
        pub fn __constructor(env: Env, admin: Address) {
            env.storage().instance().set(&ADMIN, &admin);
            env.storage().instance().set(&COUNT, &0i64);
        }
        pub fn increment(env: Env) -> Result<i64, BrokenError> {
            let count: i64 = env.storage().instance().get(&COUNT).unwrap_or(0);
            let new_count = count.checked_add(2).ok_or(BrokenError::Overflow)?; // BUG: +2, not +1
            env.storage().instance().set(&COUNT, &new_count);
            Ok(new_count)
        }
        pub fn decrement(env: Env) -> Result<i64, BrokenError> {
            let count: i64 = env.storage().instance().get(&COUNT).unwrap_or(0);
            let new_count = count.checked_sub(1).ok_or(BrokenError::Underflow)?;
            env.storage().instance().set(&COUNT, &new_count);
            Ok(new_count)
        }
        pub fn reset(env: Env) -> Result<i64, BrokenError> {
            let admin: Address = env.storage().instance().get(&ADMIN).unwrap();
            admin.require_auth();
            env.storage().instance().set(&COUNT, &0i64);
            Ok(0)
        }
        pub fn set(env: Env, value: i64) -> Result<i64, BrokenError> {
            let admin: Address = env.storage().instance().get(&ADMIN).unwrap();
            admin.require_auth();
            env.storage().instance().set(&COUNT, &value);
            Ok(value)
        }
        pub fn get(env: Env) -> i64 {
            env.storage().instance().get(&COUNT).unwrap_or(0)
        }
    }

    /// Registers the *broken* contract but reuses the counter's existing
    /// `CounterCommand` / `CounterModel` — the model still predicts correct
    /// behaviour, which is exactly what makes it diverge.
    pub struct BrokenCounterAdapter;

    impl ContractAdapter for BrokenCounterAdapter {
        type Command = CounterCommand;
        type Model = CounterModel;

        fn setup(env: &Env, addresses: &AddressPool) -> (Address, Self::Model) {
            let admin = addresses.get(0).clone();
            let contract_id = env.register(
                BrokenCounterContract,
                BrokenCounterContractArgs::__constructor(&admin),
            );
            (contract_id, CounterModel::default())
        }
    }

    impl Command<BrokenCounterAdapter> for CounterCommand {
        fn execute(&self, ctx: &ExecContext, authorizers: &[Address]) -> Outcome {
            let admin = ctx.addresses.get(0).clone();
            let client = BrokenCounterContractClient::new(ctx.env, ctx.contract_id);
            match self {
                CounterCommand::Increment => {
                    Outcome::from_try_result(client.try_increment(), true, |e| e as u32)
                }
                CounterCommand::Decrement => {
                    Outcome::from_try_result(client.try_decrement(), true, |e| e as u32)
                }
                CounterCommand::Reset => {
                    let ok = mock_admin_auth(
                        ctx.env,
                        ctx.contract_id,
                        &admin,
                        authorizers,
                        "reset",
                        soroban_sdk::vec![ctx.env],
                    );
                    Outcome::from_try_result(client.try_reset(), ok, |e| e as u32)
                }
                CounterCommand::Set(value) => {
                    let value = value.get() as i64;
                    let ok = mock_admin_auth(
                        ctx.env,
                        ctx.contract_id,
                        &admin,
                        authorizers,
                        "set",
                        soroban_sdk::vec![ctx.env, value.into_val(ctx.env)],
                    );
                    Outcome::from_try_result(client.try_set(&value), ok, |e| e as u32)
                }
            }
        }

        fn apply_to_model(
            &self,
            model: &mut CounterModel,
            _addresses: &AddressPool,
            outcome: &Outcome,
        ) {
            if !outcome.is_ok() {
                return;
            }
            // The model predicts CORRECT (+1) behaviour — that's what makes it
            // disagree with the broken contract's +2.
            match self {
                CounterCommand::Increment => {
                    model.expected_count = model.expected_count.saturating_add(1)
                }
                CounterCommand::Decrement => {
                    model.expected_count = model.expected_count.saturating_sub(1)
                }
                CounterCommand::Reset => model.expected_count = 0,
                CounterCommand::Set(value) => model.expected_count = value.get() as i64,
            }
        }
    }

    /// Distinct invariant type for the broken adapter, so `CounterValueMatchesModel`
    /// keeps implementing `Invariant` for exactly one adapter (no ambiguity).
    pub struct BrokenValueMatchesModel;

    impl Invariant<BrokenCounterAdapter> for BrokenValueMatchesModel {
        fn name(&self) -> &'static str {
            "counter-value-matches-model"
        }
        fn check(&self, ctx: &InvariantCtx<BrokenCounterAdapter>) -> Result<(), Violation> {
            let client = BrokenCounterContractClient::new(ctx.env, ctx.contract_id);
            let actual = client.get();
            if actual != ctx.model.expected_count {
                return Err(Violation {
                    invariant: self.name(),
                    message: format!(
                        "on-chain count {actual} != model's expected count {}",
                        ctx.model.expected_count
                    ),
                    step_index: ctx.step_index,
                });
            }
            Ok(())
        }
    }

    fn harness() -> Harness<BrokenCounterAdapter> {
        Harness::<BrokenCounterAdapter>::new().with_invariant(BrokenValueMatchesModel)
    }

    fn step(command: CounterCommand, authorized_indices: Vec<u8>) -> Step<CounterCommand> {
        Step {
            command,
            authorized: AuthSelection::from_indices(authorized_indices),
            advance_time: None,
        }
    }

    #[test]
    fn broken_increment_is_a_finding() {
        // One increment: the broken contract lands on 2, the model expects 1.
        let run = Run {
            steps: vec![step(CounterCommand::Increment, vec![])],
        };
        let violation = harness()
            .run(run)
            .expect_err("a broken counter must be caught by the harness");
        assert_eq!(violation.invariant, "counter-value-matches-model");
        assert_eq!(violation.step_index, 0);
    }

    use proptest::prelude::*;
    use proptest_arbitrary_interop::arb;

    proptest! {
        #[test]
        fn broken_increment_is_caught_under_any_continuation(tail in arb::<Run<CounterCommand>>()) {
            // The run always begins with an increment (the broken path). The contract
            // starts at 0, so that first step always succeeds and diverges (2 vs 1), and
            // the harness checks invariants after each step — caught at step 0 no matter
            // what proptest appends after it.
            let mut steps = vec![step(CounterCommand::Increment, vec![])];
            steps.extend(tail.steps);
            let run = Run { steps };
            prop_assert!(harness().run(run).is_err(), "broken increment slipped past the harness");
        }
    }
}
