//! Wiring the counter contract into `soro-fuzz-core`: this module is the
//! "one crate's worth of trait impls" contributors write per contract.

use arbitrary::Arbitrary;
use soroban_sdk::{
    testutils::{MockAuth, MockAuthInvoke},
    Address, Env, IntoVal,
};

use soro_fuzz_core::{
    AddressPool, Command, ContractAdapter, ExecContext, Invariant, InvariantCtx, Outcome,
    ReferenceModel, Violation,
};
use soro_fuzz_strategies::BoundedI128;

use crate::{CounterContract, CounterContractArgs, CounterContractClient};

/// Marker type for the counter contract; carries no state of its own.
pub struct CounterAdapter;

/// Shadow state: what we expect `get()` to return.
#[derive(Debug, Clone, Default)]
pub struct CounterModel {
    pub expected_count: i64,
}

impl ReferenceModel for CounterModel {}

/// `Set`'s payload is generated by `soro-fuzz-strategies`'s `BoundedI128`
/// rather than a plain `i64`: bounding it to exactly `i64`'s range (so the
/// cast to the contract's actual `i64` argument is lossless) while biasing
/// generation toward `i64::MIN`/`i64::MAX`/`0` gives the fuzzer a real shot
/// at hitting `set`'s edge cases instead of almost always picking values
/// deep in the middle of the range.
type SetValue = BoundedI128<{ i64::MIN as i128 }, { i64::MAX as i128 }>;

/// The counter's action space.
#[derive(Arbitrary, Debug, Clone)]
pub enum CounterCommand {
    Increment,
    Decrement,
    /// Admin-gated: resets the count to zero.
    Reset,
    /// Admin-gated: sets the count to an arbitrary value.
    Set(SetValue),
}

impl ContractAdapter for CounterAdapter {
    type Command = CounterCommand;
    type Model = CounterModel;

    fn setup(env: &Env, addresses: &AddressPool) -> (Address, Self::Model) {
        // contributors: this is where role assignment happens — here,
        // address 0 in the pool is always "the admin" the contract was
        // constructed with.
        let admin = addresses.get(0).clone();
        let contract_id = env.register(CounterContract, CounterContractArgs::__constructor(&admin));
        (contract_id, CounterModel::default())
    }
}

impl Command<CounterAdapter> for CounterCommand {
    fn execute(&self, ctx: &ExecContext, authorizers: &[Address]) -> Outcome {
        let admin = ctx.addresses.get(0).clone();
        let client = CounterContractClient::new(ctx.env, ctx.contract_id);

        match self {
            CounterCommand::Increment => match client.try_increment() {
                Ok(Ok(_)) => Outcome::Ok,
                Err(Ok(e)) => Outcome::DeclaredError(e as u32),
                Err(Err(invoke_err)) => Outcome::Rejected(format!("{invoke_err:?}")),
                Ok(Err(conv_err)) => panic!("increment: unexpected value conversion error: {conv_err:?}"),
            },
            CounterCommand::Decrement => match client.try_decrement() {
                Ok(Ok(_)) => Outcome::Ok,
                Err(Ok(e)) => Outcome::DeclaredError(e as u32),
                Err(Err(invoke_err)) => Outcome::Rejected(format!("{invoke_err:?}")),
                Ok(Err(conv_err)) => panic!("decrement: unexpected value conversion error: {conv_err:?}"),
            },
            CounterCommand::Reset => {
                mock_admin_auth(ctx.env, ctx.contract_id, &admin, authorizers, "reset", soroban_sdk::vec![ctx.env]);
                match client.try_reset() {
                    Ok(Ok(_)) => Outcome::Ok,
                    Err(Ok(e)) => Outcome::DeclaredError(e.get_code()),
                    Err(Err(invoke_err)) => Outcome::Rejected(format!("{invoke_err:?}")),
                    Ok(Err(conv_err)) => panic!("reset: unexpected value conversion error: {conv_err:?}"),
                }
            }
            CounterCommand::Set(value) => {
                let value = value.get() as i64;
                mock_admin_auth(
                    ctx.env,
                    ctx.contract_id,
                    &admin,
                    authorizers,
                    "set",
                    soroban_sdk::vec![ctx.env, value.into_val(ctx.env)],
                );
                match client.try_set(&value) {
                    Ok(Ok(_)) => Outcome::Ok,
                    Err(Ok(e)) => Outcome::DeclaredError(e.get_code()),
                    Err(Err(invoke_err)) => Outcome::Rejected(format!("{invoke_err:?}")),
                    Ok(Err(conv_err)) => panic!("set: unexpected value conversion error: {conv_err:?}"),
                }
            }
        }
    }

    fn apply_to_model(&self, model: &mut CounterModel, _addresses: &AddressPool, outcome: &Outcome) {
        if !outcome.is_ok() {
            return;
        }
        match self {
            CounterCommand::Increment => model.expected_count = model.expected_count.saturating_add(1),
            CounterCommand::Decrement => model.expected_count = model.expected_count.saturating_sub(1),
            CounterCommand::Reset => model.expected_count = 0,
            CounterCommand::Set(value) => model.expected_count = value.get() as i64,
        }
    }
}

/// Contract-specific invariant (not every invariant needs to live in the
/// shared `soro-fuzz-invariants` crate — this one is meaningless outside
/// the counter contract): the on-chain count must always match the shadow
/// model's expectation.
pub struct CounterValueMatchesModel;

impl Invariant<CounterAdapter> for CounterValueMatchesModel {
    fn name(&self) -> &'static str {
        "counter-value-matches-model"
    }

    fn check(&self, ctx: &InvariantCtx<CounterAdapter>) -> Result<(), Violation> {
        let client = CounterContractClient::new(ctx.env, ctx.contract_id);
        let actual = client.get();
        if actual != ctx.model.expected_count {
            return Err(Violation {
                invariant: self.name(),
                message: format!(
                    "on-chain count {actual} != model's expected count {}",
                    ctx.model.expected_count
                ),
                step_index: ctx.step_index,
            });
        }
        Ok(())
    }
}

/// Mocks `admin`'s authorization for `contract_id.fn_name(args)` iff `admin`
/// is one of the addresses this step authorized; otherwise mocks nothing,
/// so the contract's `require_auth()` legitimately fails.
fn mock_admin_auth(
    env: &Env,
    contract_id: &Address,
    admin: &Address,
    authorizers: &[Address],
    fn_name: &str,
    args: soroban_sdk::Vec<soroban_sdk::Val>,
) {
    if authorizers.contains(admin) {
        let invoke = MockAuthInvoke {
            contract: contract_id,
            fn_name,
            args,
            sub_invokes: &[],
        };
        env.mock_auths(&[MockAuth {
            address: admin,
            invoke: &invoke,
        }]);
    } else {
        env.mock_auths(&[]);
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use soro_fuzz_core::{AuthSelection, Harness, Run, Step};

    fn harness() -> Harness<CounterAdapter> {
        Harness::<CounterAdapter>::new().with_invariant(CounterValueMatchesModel)
    }

    fn step(command: CounterCommand, authorized_indices: Vec<u8>) -> Step<CounterCommand> {
        Step {
            command,
            authorized: AuthSelection::from_indices(authorized_indices),
            advance_time: None,
        }
    }

    #[test]
    fn increment_then_decrement_round_trips() {
        let run = Run {
            steps: vec![
                step(CounterCommand::Increment, vec![]),
                step(CounterCommand::Increment, vec![]),
                step(CounterCommand::Decrement, vec![]),
            ],
        };
        assert!(harness().run(run).is_ok());
    }

    #[test]
    fn set_without_admin_auth_is_rejected_not_a_panic() {
        // Address 0 is the admin (see `CounterAdapter::setup`); authorizing
        // index 1 instead means the admin never signed, so `set` should be
        // host-rejected (Outcome::Rejected), not crash the run.
        let run = Run {
            steps: vec![step(CounterCommand::Set(SetValue::new(42)), vec![1])],
        };
        assert!(harness().run(run).is_ok());
    }

    #[test]
    fn set_with_admin_auth_succeeds() {
        let run = Run {
            steps: vec![step(CounterCommand::Set(SetValue::new(42)), vec![0])],
        };
        assert!(harness().run(run).is_ok());
    }

    #[test]
    fn single_decrement_from_initial_state_runs_clean() {
        let run = Run {
            steps: vec![step(CounterCommand::Decrement, vec![])],
        };
        assert!(harness().run(run).is_ok());
    }

    #[test]
    fn value_matches_model_invariant_catches_real_divergence() {
        // Exercise the invariant directly against a live contract, with a
        // shadow model deliberately built to disagree with it — proves
        // `CounterValueMatchesModel` actually detects the class of bug it
        // exists to catch, rather than only ever passing by construction.
        use soroban_sdk::testutils::Address as _;
        let env = Env::default();
        let admin = Address::generate(&env);
        let contract_id = env.register(CounterContract, CounterContractArgs::__constructor(&admin));
        let client = CounterContractClient::new(&env, &contract_id);
        client.increment();
        client.increment();

        let wrong_model = CounterModel { expected_count: 0 };
        let pool = AddressPool::generate(&env, 1);
        let ctx = InvariantCtx {
            env: &env,
            contract_id: &contract_id,
            model: &wrong_model,
            command: &CounterCommand::Increment,
            last_outcome: &Outcome::Ok,
            authorizers: &[],
            addresses: &pool,
            step_index: 0,
        };
        assert!(CounterValueMatchesModel.check(&ctx).is_err());
    }
}
